//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenIZAdmin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenIZAdmin.Localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        public static string Acknowledge {
            get {
                return ResourceManager.GetString("Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        public static string Acknowledged {
            get {
                return ResourceManager.GetString("Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activated successfully.
        /// </summary>
        public static string ActivatedSuccessfully {
            get {
                return ResourceManager.GetString("ActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative contact email.
        /// </summary>
        public static string AdministrativeContactEmail {
            get {
                return ResourceManager.GetString("AdministrativeContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative contact name.
        /// </summary>
        public static string AdministrativeContactName {
            get {
                return ResourceManager.GetString("AdministrativeContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applet Id.
        /// </summary>
        public static string AppletId {
            get {
                return ResourceManager.GetString("AppletId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applets.
        /// </summary>
        public static string Applets {
            get {
                return ResourceManager.GetString("Applets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning Authorities.
        /// </summary>
        public static string AssigningAuthorities {
            get {
                return ResourceManager.GetString("AssigningAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning authority.
        /// </summary>
        public static string AssigningAuthority {
            get {
                return ResourceManager.GetString("AssigningAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigning Device ID.
        /// </summary>
        public static string AssigningDeviceId {
            get {
                return ResourceManager.GetString("AssigningDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Override.
        /// </summary>
        public static string CanOverride {
            get {
                return ResourceManager.GetString("CanOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Requests.
        /// </summary>
        public static string CertificateRequests {
            get {
                return ResourceManager.GetString("CertificateRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate signing request successfully accepted.
        /// </summary>
        public static string CertificateSigningRequestAccepted {
            get {
                return ResourceManager.GetString("CertificateSigningRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Signing Request Id.
        /// </summary>
        public static string CertificateSigningRequestId {
            get {
                return ResourceManager.GetString("CertificateSigningRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate signing request successfully submitted.
        /// </summary>
        public static string CertificateSigningRequestSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("CertificateSigningRequestSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Name.
        /// </summary>
        public static string CommonName {
            get {
                return ResourceManager.GetString("CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept.
        /// </summary>
        public static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Name.
        /// </summary>
        public static string ConceptName {
            get {
                return ResourceManager.GetString("ConceptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepts.
        /// </summary>
        public static string Concepts {
            get {
                return ResourceManager.GetString("Concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Search Results.
        /// </summary>
        public static string ConceptSearchResults {
            get {
                return ResourceManager.GetString("ConceptSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to concept sets.
        /// </summary>
        public static string ConceptSets {
            get {
                return ResourceManager.GetString("ConceptSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm password do not match.
        /// </summary>
        public static string ConfirmPasswordMatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirm password field is required.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Assigning Authority.
        /// </summary>
        public static string CreateAssigningAuthority {
            get {
                return ResourceManager.GetString("CreateAssigningAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Concept.
        /// </summary>
        public static string CreateConcept {
            get {
                return ResourceManager.GetString("CreateConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Device.
        /// </summary>
        public static string CreateDevice {
            get {
                return ResourceManager.GetString("CreateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created successfully.
        /// </summary>
        public static string CreatedSuccessfully {
            get {
                return ResourceManager.GetString("CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Place.
        /// </summary>
        public static string CreatePlace {
            get {
                return ResourceManager.GetString("CreatePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Policy.
        /// </summary>
        public static string CreatePolicy {
            get {
                return ResourceManager.GetString("CreatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Provider.
        /// </summary>
        public static string CreateProvider {
            get {
                return ResourceManager.GetString("CreateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Realm.
        /// </summary>
        public static string CurrentRealm {
            get {
                return ResourceManager.GetString("CurrentRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Requested.
        /// </summary>
        public static string DateRequested {
            get {
                return ResourceManager.GetString("DateRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deactivated successfully.
        /// </summary>
        public static string DeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("DeactivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description field must be not exceed 1000 characters.
        /// </summary>
        public static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguished name.
        /// </summary>
        public static string DistinguishedName {
            get {
                return ResourceManager.GetString("DistinguishedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        public static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edited successfully.
        /// </summary>
        public static string EditedSuccessfully {
            get {
                return ResourceManager.GetString("EditedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Policy.
        /// </summary>
        public static string EditPolicy {
            get {
                return ResourceManager.GetString("EditPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Provider.
        /// </summary>
        public static string EditProvider {
            get {
                return ResourceManager.GetString("EditProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate.
        /// </summary>
        public static string Elevate {
            get {
                return ResourceManager.GetString("Elevate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Password.
        /// </summary>
        public static string ExistingPassword {
            get {
                return ResourceManager.GetString("ExistingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The existing password field is required.
        /// </summary>
        public static string ExistingPasswordRequired {
            get {
                return ResourceManager.GetString("ExistingPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        public static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a facility.
        /// </summary>
        public static string FacilityRequired {
            get {
                return ResourceManager.GetString("FacilityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Names.
        /// </summary>
        public static string FamilyNames {
            get {
                return ResourceManager.GetString("FamilyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field must not exceed 255 characters.
        /// </summary>
        public static string FirstNameTooLong {
            get {
                return ResourceManager.GetString("FirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant.
        /// </summary>
        public static string Grant {
            get {
                return ResourceManager.GetString("Grant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants.
        /// </summary>
        public static string Grants {
            get {
                return ResourceManager.GetString("Grants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a grant.
        /// </summary>
        public static string GrantsRequired {
            get {
                return ResourceManager.GetString("GrantsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Facility.
        /// </summary>
        public static string HealthFacility {
            get {
                return ResourceManager.GetString("HealthFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Priority.
        /// </summary>
        public static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7CX4.
        /// </summary>
        public static string HL7CX4 {
            get {
                return ResourceManager.GetString("HL7CX4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password.
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search, please check your search criteria.
        /// </summary>
        public static string InvalidSearch {
            get {
                return ResourceManager.GetString("InvalidSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Public.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join New Realm.
        /// </summary>
        public static string JoinNewRealm {
            get {
                return ResourceManager.GetString("JoinNewRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Realm.
        /// </summary>
        public static string JoinRealm {
            get {
                return ResourceManager.GetString("JoinRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login time.
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field must not exceed 255 characters.
        /// </summary>
        public static string LastNameTooLong {
            get {
                return ResourceManager.GetString("LastNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Realm.
        /// </summary>
        public static string LeaveRealm {
            get {
                return ResourceManager.GetString("LeaveRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out?.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a message.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        public static string Mnemonic {
            get {
                return ResourceManager.GetString("Mnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mnemonic field is required.
        /// </summary>
        public static string MnemonicRequired {
            get {
                return ResourceManager.GetString("MnemonicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mnemonic field must not exceed 255 characters.
        /// </summary>
        public static string MnemonicTooLong {
            get {
                return ResourceManager.GetString("MnemonicTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field must not exceed 255 characters.
        /// </summary>
        public static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional details have been provided.
        /// </summary>
        public static string NoAdditionalDetails {
            get {
                return ResourceManager.GetString("NoAdditionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices have been added.
        /// </summary>
        public static string NoDevicesAdded {
            get {
                return ResourceManager.GetString("NoDevicesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new certificate signing requests have been submitted.
        /// </summary>
        public static string NoNewCertificateSigningRequestsSubmitted {
            get {
                return ResourceManager.GetString("NoNewCertificateSigningRequestsSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No policies found.
        /// </summary>
        public static string NoPoliciesFound {
            get {
                return ResourceManager.GetString("NoPoliciesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No providers found.
        /// </summary>
        public static string NoProvidersFound {
            get {
                return ResourceManager.GetString("NoProvidersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roles have been added.
        /// </summary>
        public static string NoRolesAdded {
            get {
                return ResourceManager.GetString("NoRolesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user roles have been added.
        /// </summary>
        public static string NoUserRolesAdded {
            get {
                return ResourceManager.GetString("NoUserRolesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users have been added.
        /// </summary>
        public static string NoUsersAdded {
            get {
                return ResourceManager.GetString("NoUsersAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oid.
        /// </summary>
        public static string Oid {
            get {
                return ResourceManager.GetString("Oid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID.
        /// </summary>
        public static string OIDAllCaps {
            get {
                return ResourceManager.GetString("OIDAllCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oid field is required.
        /// </summary>
        public static string OidRequired {
            get {
                return ResourceManager.GetString("OidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Type.
        /// </summary>
        public static string PhoneType {
            get {
                return ResourceManager.GetString("PhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Search Results.
        /// </summary>
        public static string PlaceSearchResults {
            get {
                return ResourceManager.GetString("PlaceSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Search Results.
        /// </summary>
        public static string PolicySearchResults {
            get {
                return ResourceManager.GetString("PolicySearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string Providers {
            get {
                return ResourceManager.GetString("Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Specialty.
        /// </summary>
        public static string ProviderSpecialty {
            get {
                return ResourceManager.GetString("ProviderSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm.
        /// </summary>
        public static string Realm {
            get {
                return ResourceManager.GetString("Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm joined successfully.
        /// </summary>
        public static string RealmJoinedSuccessfully {
            get {
                return ResourceManager.GetString("RealmJoinedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm left successfully.
        /// </summary>
        public static string RealmLeftSuccessfully {
            get {
                return ResourceManager.GetString("RealmLeftSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm Management.
        /// </summary>
        public static string RealmManagement {
            get {
                return ResourceManager.GetString("RealmManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm switched successfully.
        /// </summary>
        public static string RealmSwitchedSuccessfully {
            get {
                return ResourceManager.GetString("RealmSwitchedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a role.
        /// </summary>
        public static string RolesRequired {
            get {
                return ResourceManager.GetString("RolesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role View.
        /// </summary>
        public static string RoleView {
            get {
                return ResourceManager.GetString("RoleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Providers.
        /// </summary>
        public static string SearchProviders {
            get {
                return ResourceManager.GetString("SearchProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term.
        /// </summary>
        public static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Type.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a search type.
        /// </summary>
        public static string SearchTypeRequired {
            get {
                return ResourceManager.GetString("SearchTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security application.
        /// </summary>
        public static string SecurityApplication {
            get {
                return ResourceManager.GetString("SecurityApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session timed out.
        /// </summary>
        public static string SessionTimedOut {
            get {
                return ResourceManager.GetString("SessionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Time.
        /// </summary>
        public static string SubmissionTime {
            get {
                return ResourceManager.GetString("SubmissionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to accept certificate signing request.
        /// </summary>
        public static string UnableToAcceptCertificateSigningRequest {
            get {
                return ResourceManager.GetString("UnableToAcceptCertificateSigningRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to activate.
        /// </summary>
        public static string UnableToActivate {
            get {
                return ResourceManager.GetString("UnableToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password.
        /// </summary>
        public static string UnableToChangePassword {
            get {
                return ResourceManager.GetString("UnableToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create.
        /// </summary>
        public static string UnableToCreate {
            get {
                return ResourceManager.GetString("UnableToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deactivate.
        /// </summary>
        public static string UnableToDeactivate {
            get {
                return ResourceManager.GetString("UnableToDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete.
        /// </summary>
        public static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find specified certificate.
        /// </summary>
        public static string UnableToFindSpecifiedCertificate {
            get {
                return ResourceManager.GetString("UnableToFindSpecifiedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find specified certificate signing request.
        /// </summary>
        public static string UnableToFindSpecifiedCertificateSigningRequest {
            get {
                return ResourceManager.GetString("UnableToFindSpecifiedCertificateSigningRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to join realm.
        /// </summary>
        public static string UnableToJoinRealm {
            get {
                return ResourceManager.GetString("UnableToJoinRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to leave realm.
        /// </summary>
        public static string UnableToLeaveRealm {
            get {
                return ResourceManager.GetString("UnableToLeaveRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reject certificate signing request.
        /// </summary>
        public static string UnableToRejectCertificateSigningRequest {
            get {
                return ResourceManager.GetString("UnableToRejectCertificateSigningRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve.
        /// </summary>
        public static string UnableToRetrieve {
            get {
                return ResourceManager.GetString("UnableToRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve certificate list.
        /// </summary>
        public static string UnableToRetrieveCertificateList {
            get {
                return ResourceManager.GetString("UnableToRetrieveCertificateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve certificate revocation list.
        /// </summary>
        public static string UnableToRetrieveCertificateRevocationlist {
            get {
                return ResourceManager.GetString("UnableToRetrieveCertificateRevocationlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve certificate signing request list.
        /// </summary>
        public static string UnableToRetrieveCertificateSigningRequestList {
            get {
                return ResourceManager.GetString("UnableToRetrieveCertificateSigningRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve device list.
        /// </summary>
        public static string UnableToRetrieveDeviceList {
            get {
                return ResourceManager.GetString("UnableToRetrieveDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve place list.
        /// </summary>
        public static string UnableToRetrievePlaceList {
            get {
                return ResourceManager.GetString("UnableToRetrievePlaceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve role list.
        /// </summary>
        public static string UnableToRetrieveRoleList {
            get {
                return ResourceManager.GetString("UnableToRetrieveRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve user list.
        /// </summary>
        public static string UnableToRetrieveUserList {
            get {
                return ResourceManager.GetString("UnableToRetrieveUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit certificate signing request.
        /// </summary>
        public static string UnableToSubmitCertificateSigningRequest {
            get {
                return ResourceManager.GetString("UnableToSubmitCertificateSigningRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to switch realm.
        /// </summary>
        public static string UnableToSwitchRealm {
            get {
                return ResourceManager.GetString("UnableToSwitchRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update.
        /// </summary>
        public static string UnableToUpdate {
            get {
                return ResourceManager.GetString("UnableToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload applet.
        /// </summary>
        public static string UnableToUploadApplet {
            get {
                return ResourceManager.GetString("UnableToUploadApplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Time.
        /// </summary>
        public static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field must be between 1 and 255 characters.
        /// </summary>
        public static string UsernameTooLong {
            get {
                return ResourceManager.GetString("UsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User View.
        /// </summary>
        public static string UserView {
            get {
                return ResourceManager.GetString("UserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
