//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenIZAdmin.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenIZAdmin.Localization.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative contact email.
        /// </summary>
        public static string AdministrativeContactEmail {
            get {
                return ResourceManager.GetString("AdministrativeContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative contact name.
        /// </summary>
        public static string AdministrativeContactName {
            get {
                return ResourceManager.GetString("AdministrativeContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applet Id.
        /// </summary>
        public static string AppletId {
            get {
                return ResourceManager.GetString("AppletId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applets.
        /// </summary>
        public static string Applets {
            get {
                return ResourceManager.GetString("Applets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Id.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Override.
        /// </summary>
        public static string CanOverride {
            get {
                return ResourceManager.GetString("CanOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Requests.
        /// </summary>
        public static string CertificateRequests {
            get {
                return ResourceManager.GetString("CertificateRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Signing Request Id.
        /// </summary>
        public static string CertificateSigningRequestId {
            get {
                return ResourceManager.GetString("CertificateSigningRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Name.
        /// </summary>
        public static string CommonName {
            get {
                return ResourceManager.GetString("CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept.
        /// </summary>
        public static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept created successfully.
        /// </summary>
        public static string ConceptCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ConceptCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Name.
        /// </summary>
        public static string ConceptName {
            get {
                return ResourceManager.GetString("ConceptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept not found.
        /// </summary>
        public static string ConceptNotFound {
            get {
                return ResourceManager.GetString("ConceptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepts.
        /// </summary>
        public static string Concepts {
            get {
                return ResourceManager.GetString("Concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concept Search Results.
        /// </summary>
        public static string ConceptSearchResults {
            get {
                return ResourceManager.GetString("ConceptSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Concept.
        /// </summary>
        public static string CreateConcept {
            get {
                return ResourceManager.GetString("CreateConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Device.
        /// </summary>
        public static string CreateDevice {
            get {
                return ResourceManager.GetString("CreateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Place.
        /// </summary>
        public static string CreatePlace {
            get {
                return ResourceManager.GetString("CreatePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Policy.
        /// </summary>
        public static string CreatePolicy {
            get {
                return ResourceManager.GetString("CreatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string CreateRole {
            get {
                return ResourceManager.GetString("CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Realm.
        /// </summary>
        public static string CurrentRealm {
            get {
                return ResourceManager.GetString("CurrentRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Requested.
        /// </summary>
        public static string DateRequested {
            get {
                return ResourceManager.GetString("DateRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found.
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguished name.
        /// </summary>
        public static string DistinguishedName {
            get {
                return ResourceManager.GetString("DistinguishedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate.
        /// </summary>
        public static string Elevate {
            get {
                return ResourceManager.GetString("Elevate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name field must not exceed 255 characters.
        /// </summary>
        public static string FirstNameTooLong {
            get {
                return ResourceManager.GetString("FirstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant.
        /// </summary>
        public static string Grant {
            get {
                return ResourceManager.GetString("Grant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants.
        /// </summary>
        public static string Grants {
            get {
                return ResourceManager.GetString("Grants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a grant.
        /// </summary>
        public static string GrantsRequired {
            get {
                return ResourceManager.GetString("GrantsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password.
        /// </summary>
        public static string IncorrectUsernameOrPassword {
            get {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Public.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join New Realm.
        /// </summary>
        public static string JoinNewRealm {
            get {
                return ResourceManager.GetString("JoinNewRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Realm.
        /// </summary>
        public static string JoinRealm {
            get {
                return ResourceManager.GetString("JoinRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name field must not exceed 255 characters.
        /// </summary>
        public static string LastNameTooLong {
            get {
                return ResourceManager.GetString("LastNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Realm.
        /// </summary>
        public static string LeaveRealm {
            get {
                return ResourceManager.GetString("LeaveRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out?.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        public static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnemonic.
        /// </summary>
        public static string Mnemonic {
            get {
                return ResourceManager.GetString("Mnemonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mnemonic field is required.
        /// </summary>
        public static string MnemonicRequired {
            get {
                return ResourceManager.GetString("MnemonicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mnemonic field must not exceed 255 characters.
        /// </summary>
        public static string MnemonicTooLong {
            get {
                return ResourceManager.GetString("MnemonicTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field must not exceed 255 characters.
        /// </summary>
        public static string NameTooLong {
            get {
                return ResourceManager.GetString("NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional details have been provided.
        /// </summary>
        public static string NoAdditionalDetails {
            get {
                return ResourceManager.GetString("NoAdditionalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No concepts found.
        /// </summary>
        public static string NoConceptsFound {
            get {
                return ResourceManager.GetString("NoConceptsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices have been added.
        /// </summary>
        public static string NoDevicesAdded {
            get {
                return ResourceManager.GetString("NoDevicesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new certificate signing requests have been submitted.
        /// </summary>
        public static string NoNewCertificateSigningRequestsSubmitted {
            get {
                return ResourceManager.GetString("NoNewCertificateSigningRequestsSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places found.
        /// </summary>
        public static string NoPlacesFound {
            get {
                return ResourceManager.GetString("NoPlacesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No policies found.
        /// </summary>
        public static string NoPoliciesFound {
            get {
                return ResourceManager.GetString("NoPoliciesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roles have been added.
        /// </summary>
        public static string NoRolesAdded {
            get {
                return ResourceManager.GetString("NoRolesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user roles have been added.
        /// </summary>
        public static string NoUserRolesAdded {
            get {
                return ResourceManager.GetString("NoUserRolesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users have been added.
        /// </summary>
        public static string NoUsersAdded {
            get {
                return ResourceManager.GetString("NoUsersAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oid.
        /// </summary>
        public static string Oid {
            get {
                return ResourceManager.GetString("Oid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oid field is required.
        /// </summary>
        public static string OidRequired {
            get {
                return ResourceManager.GetString("OidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place not found.
        /// </summary>
        public static string PlaceNotFound {
            get {
                return ResourceManager.GetString("PlaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Search Results.
        /// </summary>
        public static string PlaceSearchResults {
            get {
                return ResourceManager.GetString("PlaceSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy not found.
        /// </summary>
        public static string PolicyNotFound {
            get {
                return ResourceManager.GetString("PolicyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Search Results.
        /// </summary>
        public static string PolicySearchResults {
            get {
                return ResourceManager.GetString("PolicySearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realm Management.
        /// </summary>
        public static string RealmManagement {
            get {
                return ResourceManager.GetString("RealmManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Id.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a role.
        /// </summary>
        public static string RolesRequired {
            get {
                return ResourceManager.GetString("RolesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role View.
        /// </summary>
        public static string RoleView {
            get {
                return ResourceManager.GetString("RoleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Term.
        /// </summary>
        public static string SearchTerm {
            get {
                return ResourceManager.GetString("SearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Type.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a search type.
        /// </summary>
        public static string SearchTypeRequired {
            get {
                return ResourceManager.GetString("SearchTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Time.
        /// </summary>
        public static string SubmissionTime {
            get {
                return ResourceManager.GetString("SubmissionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create concept.
        /// </summary>
        public static string UnableToCreateConcept {
            get {
                return ResourceManager.GetString("UnableToCreateConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create policy.
        /// </summary>
        public static string UnableToCreatePolicy {
            get {
                return ResourceManager.GetString("UnableToCreatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve device list.
        /// </summary>
        public static string UnableToRetrieveDeviceList {
            get {
                return ResourceManager.GetString("UnableToRetrieveDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve role list.
        /// </summary>
        public static string UnableToRetrieveRoleList {
            get {
                return ResourceManager.GetString("UnableToRetrieveRoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve user list.
        /// </summary>
        public static string UnableToRetrieveUserList {
            get {
                return ResourceManager.GetString("UnableToRetrieveUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update device.
        /// </summary>
        public static string UnableToUpdateDevice {
            get {
                return ResourceManager.GetString("UnableToUpdateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update place.
        /// </summary>
        public static string UnableToUpdatePlace {
            get {
                return ResourceManager.GetString("UnableToUpdatePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update profile.
        /// </summary>
        public static string UnableToUpdateProfile {
            get {
                return ResourceManager.GetString("UnableToUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update user.
        /// </summary>
        public static string UnableToUpdateUser {
            get {
                return ResourceManager.GetString("UnableToUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Time.
        /// </summary>
        public static string UpdatedTime {
            get {
                return ResourceManager.GetString("UpdatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update role.
        /// </summary>
        public static string UpdateToUpdateRole {
            get {
                return ResourceManager.GetString("UpdateToUpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username field must be between 1 and 255 characters.
        /// </summary>
        public static string UsernameTooLong {
            get {
                return ResourceManager.GetString("UsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User View.
        /// </summary>
        public static string UserView {
            get {
                return ResourceManager.GetString("UserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
